// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gotemplate/internal/adapter/http/controllers/ping"
	"gotemplate/internal/config"
	"gotemplate/internal/infrastructure/http"
	"gotemplate/internal/infrastructure/wire"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*App, func(), error) {
	appConfig := wire.ProvideAppConfig(cfg)
	httpConfig := wire.ProvideHTTPConfig(cfg)
	controller := ping.NewController()
	server, cleanup, err := http.NewServer(appConfig, httpConfig, controller)
	if err != nil {
		return nil, nil, err
	}
	app := NewApp(server)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

type App struct {
	Server *http.Server
}

func NewApp(server *http.Server) *App {
	return &App{
		Server: server,
	}
}
